version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Admin1234
      - POSTGRES_DB=drones
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
  drone-server:
    build: ./
    container_name: drone-rest-server
    ports:
      - "8888:80"
    depends_on:
      - db
    volumes:
      - /Users/ahmednasser/.m2:/root/.m2/
    environment:
      - SERVER_PORT=80
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=drones
      - DB_USERNAME=root
      - DB_PASSWORD=Admin1234
    restart: unless-stopped